# -*- coding: utf-8 -*-
"""
Drag & Drop Tests (Quote Builder)
=================================
Simulates the payload generated by the QuoteBuilder UI after drag & drop
operations, verifying that the backend correctly processes reordered lines
and changed lot_ids for inter-section draggability.
"""

from odoo.tests import common, tagged

@tagged('post_install', '-at_install', 'construction_sale', 'dnd')
class TestQuoteDragDrop(common.TransactionCase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.partner = cls.env['res.partner'].create({'name': 'Client DnD Test'})
        cls.chantier = cls.env['construction.chantier'].create({
            'name': 'Chantier DnD',
            'partner_id': cls.partner.id,
        })
        
        # Create two sections (Lots)
        cls.lot_a = cls.env['construction.lot'].create({
            'name': 'Gros Oeuvre',
            'code': 'L01',
            'chantier_id': cls.chantier.id,
        })
        cls.lot_b = cls.env['construction.lot'].create({
            'name': 'Peinture',
            'code': 'L02',
            'chantier_id': cls.chantier.id,
        })

        # Test Products
        cls.product_1 = cls.env['product.product'].create({'name': 'Béton', 'type': 'service'})
        cls.product_2 = cls.env['product.product'].create({'name': 'Acier', 'type': 'service'})
        cls.product_3 = cls.env['product.product'].create({'name': 'Peinture Blanche', 'type': 'service'})

    def test_01_reorder_within_same_section(self):
        """
        1. Reorder au sein d'une même section:
        Simulate UI sending lines in a new order after DnD within Lot A.
        """
        # Original: [Béton, Acier]
        # Drop UI outcome: [Acier, Béton]
        order_line_data = [
            (0, 0, {'product_id': self.product_2.id, 'lot_id': self.lot_a.id, 'product_uom_qty': 1}), # Acier first
            (0, 0, {'product_id': self.product_1.id, 'lot_id': self.lot_a.id, 'product_uom_qty': 2}), # Béton second
        ]
        
        order = self.env['sale.order'].create_from_spa(
            self.chantier.id,
            self.partner.id,
            order_line_data
        )
        
        self.assertEqual(len(order.order_line), 2)
        # Odoo native sequence follows creation order in commands
        self.assertEqual(order.order_line[0].product_id, self.product_2)
        self.assertEqual(order.order_line[1].product_id, self.product_1)

    def test_02_reorder_inter_section(self):
        """
        2. Reorder inter-section (QuoteLine de SecA -> SecB):
        Simulate UI modifying the lot_id of a line when dropped in a new section.
        """
        # UI state: Acier moved from Lot A to Lot B
        order_line_data = [
            (0, 0, {'product_id': self.product_1.id, 'lot_id': self.lot_a.id, 'product_uom_qty': 1}), # Béton in Lot A
            (0, 0, {'product_id': self.product_3.id, 'lot_id': self.lot_b.id, 'product_uom_qty': 5}), # Peinture in Lot B
            (0, 0, {'product_id': self.product_2.id, 'lot_id': self.lot_b.id, 'product_uom_qty': 2}), # Acier moved to Lot B
        ]
        
        order = self.env['sale.order'].create_from_spa(
            self.chantier.id,
            self.partner.id,
            order_line_data
        )
        
        self.assertEqual(len(order.order_line.filtered(lambda l: l.lot_id == self.lot_a)), 1)
        self.assertEqual(len(order.order_line.filtered(lambda l: l.lot_id == self.lot_b)), 2)
        
        # Verify Acier is in Lot B
        acier_line = order.order_line.filtered(lambda l: l.product_id == self.product_2)
        self.assertEqual(acier_line.lot_id, self.lot_b, "Line lot_id should be updated based on drop zone")

    def test_03_drop_on_empty_section(self):
        """
        3. Drop sur une section vide:
        Simulate moving a line to a section that has no other lines yet.
        """
        # Lot B is empty before. We drop Béton into Lot B.
        order_line_data = [
            (0, 0, {'product_id': self.product_1.id, 'lot_id': self.lot_b.id, 'product_uom_qty': 1}), # Béton moved to empty Lot B
        ]
        
        order = self.env['sale.order'].create_from_spa(
            self.chantier.id,
            self.partner.id,
            order_line_data
        )
        
        # Ensure the line was created and assigned to the previously empty lot
        self.assertEqual(len(order.order_line), 1)
        self.assertEqual(order.order_line.lot_id, self.lot_b)
