[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/custom_addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$4tw7ByCE8H5PCWGMcW6NsQ$TARfNW0z4UzIErS0d9VZUHVQXwDY7vPZyUq/04ISb.6.HZ71FL8Yq9uWzJN.wQcLkB9CrcwCpFT126fmAcTnpA
xmlrpc_port = 8069
logfile = /var/log/odoo/odoo.log
log_level = debug
dev_mode = all

