# -*- coding: utf-8 -*-
"""
Contract Deliverable Model
Manages documents and deliverables attached to contracts
Includes planning documents, certificates, and technical documentation
"""

from odoo import models, fields, api, _
from odoo.exceptions import ValidationError
import base64
import logging

_logger = logging.getLogger(__name__)

from ..config.contract_constants import DELIVERABLE_TYPES


class ConstructionContractDeliverable(models.Model):
    """
    Contract Deliverable

    Documents and deliverables that are part of the contract
    Can be automatically generated or manually uploaded
    """

    _name = 'construction.contract.deliverable'
    _description = 'Contract Deliverable'
    _order = 'sequence, deliverable_type, name'

    # ============================================================
    # BASIC INFORMATION
    # ============================================================

    contract_id = fields.Many2one(
        'construction.contract',
        string='Contract',
        required=True,
        ondelete='cascade',
        index=True,
        help="Related contract"
    )

    sequence = fields.Integer(
        string='Sequence',
        default=10,
        help="Order of deliverables in contract"
    )

    name = fields.Char(
        string='Deliverable Name',
        required=True,
        help="Name of the deliverable"
    )

    deliverable_type = fields.Selection(
        selection=DELIVERABLE_TYPES,
        string='Type',
        required=True,
        default='other',
        help="Type of deliverable"
    )

    description = fields.Text(
        string='Description',
        help="Detailed description of the deliverable"
    )

    # ============================================================
    # DOCUMENT STORAGE
    # ============================================================

    document = fields.Binary(
        string='Document File',
        attachment=True,
        help="Uploaded document file"
    )

    document_name = fields.Char(
        string='Filename',
        help="Name of the uploaded file"
    )

    document_url = fields.Char(
        string='Document URL',
        help="External URL to document (if not uploaded)"
    )

    # ============================================================
    # STATUS & VALIDATION
    # ============================================================

    is_mandatory = fields.Boolean(
        string='Mandatory',
        default=True,
        help="If checked, this deliverable is required for contract completion"
    )

    included_in_contract = fields.Boolean(
        string='Include in Contract PDF',
        default=True,
        help="If checked, this document will be annexed to the contract PDF"
    )

    merge_in_contract = fields.Boolean(
        string='Merge in Contract',
        default=False,
        help="If checked, this document will be merged into the main contract PDF"
    )

    merge_order = fields.Integer(
        string='Merge Order',
        default=10,
        help="Order of appearance in the merged contract (lower numbers appear first)"
    )

    is_generated = fields.Boolean(
        string='Auto-Generated',
        default=False,
        help="True if deliverable was automatically generated by the system"
    )

    generation_date = fields.Datetime(
        string='Generation Date',
        help="Date when deliverable was auto-generated"
    )

    # ============================================================
    # SOURCE REFERENCES
    # ============================================================

    source_model = fields.Char(
        string='Source Model',
        help="Odoo model that generated this deliverable (e.g., construction.planning.task)"
    )

    source_id = fields.Integer(
        string='Source Record ID',
        help="ID of the record that generated this deliverable"
    )

    # For planning deliverables
    planning_task_ids = fields.Many2many(
        'construction.planning.task',
        'deliverable_planning_task_rel',
        'deliverable_id',
        'task_id',
        string='Related Planning Tasks',
        help="Planning tasks included in this deliverable"
    )

    # For document deliverables from subcontractor
    partner_document_type = fields.Selection([
        ('urssaf', 'URSSAF Certificate'),
        ('kbis', 'KBIS Extract'),
        ('insurance', 'Insurance Certificate'),
        ('rib', 'Bank Details (RIB)'),
    ], string='Partner Document Type', help="Type of document from subcontractor profile")

    # ============================================================
    # METADATA
    # ============================================================

    file_size = fields.Integer(
        string='File Size (bytes)',
        compute='_compute_file_size',
        store=True,
        help="Size of uploaded document in bytes"
    )

    file_size_readable = fields.Char(
        string='File Size',
        compute='_compute_file_size',
        help="Human-readable file size"
    )

    mime_type = fields.Char(
        string='MIME Type',
        help="Document MIME type (e.g., application/pdf)"
    )

    # ============================================================
    # COMPUTED FIELDS
    # ============================================================

    @api.depends('document')
    def _compute_file_size(self):
        """Calculate file size from binary data"""
        for deliverable in self:
            if deliverable.document:
                try:
                    decoded = base64.b64decode(deliverable.document)
                    size_bytes = len(decoded)
                    deliverable.file_size = size_bytes

                    if size_bytes < 1024:
                        deliverable.file_size_readable = f"{size_bytes} B"
                    elif size_bytes < 1024 * 1024:
                        deliverable.file_size_readable = f"{size_bytes / 1024:.1f} KB"
                    else:
                        deliverable.file_size_readable = f"{size_bytes / (1024 * 1024):.1f} MB"
                except Exception:
                    _logger.warning("Failed to decode document for deliverable %s", deliverable.name)
                    deliverable.file_size = 0
                    deliverable.file_size_readable = "0 B"
            else:
                deliverable.file_size = 0
                deliverable.file_size_readable = "0 B"

    # ============================================================
    # CONSTRAINTS
    # ============================================================

    @api.constrains('document', 'document_url')
    def _check_has_document_or_url(self):
        """Ensure either file or URL is provided"""
        for deliverable in self:
            if not deliverable.document and not deliverable.document_url:
                raise ValidationError(_(
                    "Deliverable '%s' must have either a document file or a URL."
                ) % deliverable.name)

    @api.constrains('file_size')
    def _check_file_size_limit(self):
        """Limit file size to 20 MB"""
        MAX_SIZE = 20 * 1024 * 1024  # 20 MB

        for deliverable in self:
            if deliverable.file_size > MAX_SIZE:
                raise ValidationError(_(
                    "File '%s' is too large (%.1f MB). Maximum allowed: 20 MB"
                ) % (deliverable.document_name, deliverable.file_size / (1024 * 1024)))

    # ============================================================
    # BUSINESS METHODS
    # ============================================================

    @api.model
    def create_from_planning(self, contract, planning_tasks):
        """
        Auto-generate planning deliverable from planning tasks

        Args:
            contract: construction.contract record
            planning_tasks: recordset of construction.planning.task

        Returns:
            construction.contract.deliverable: Created deliverable
        """
        # Generate planning report
        planning_report = contract.chantier_id._generate_planning_report(planning_tasks)

        return self.create({
            'contract_id': contract.id,
            'name': _('Subcontractor Planning'),
            'deliverable_type': 'planning_subcontractor',
            'description': _('Detailed planning for subcontractor %s') % contract.subcontractor_id.name,
            'document': planning_report,
            'document_name': f'planning_{contract.name}.pdf',
            'is_generated': True,
            'generation_date': fields.Datetime.now(),
            'planning_task_ids': [(6, 0, planning_tasks.ids)],
            'source_model': 'construction.planning.task',
            'is_mandatory': True,
            'included_in_contract': True,
        })

    @api.model
    def create_from_partner_document(self, contract, document_type):
        """
        Auto-generate deliverable from subcontractor document
        Uses documents from blg_contacts_extension

        Args:
            contract: construction.contract record
            document_type: str (urssaf, kbis, insurance, rib)

        Returns:
            construction.contract.deliverable: Created deliverable
        """
        partner = contract.subcontractor_id

        # Map document types to partner fields
        doc_mapping = {
            'urssaf': {
                'field': 'document_URSSAF',
                'filename_field': 'document_URSSAF_filename',
                'name': _('URSSAF Certificate'),
            },
            'kbis': {
                'field': 'document_KBIS',
                'filename_field': 'document_KBIS_filename',
                'name': _('KBIS Extract'),
            },
            'insurance': {
                'field': 'document_insurance',
                'filename_field': 'document_insurance_filename',
                'name': _('Insurance Certificate'),
            },
            'rib': {
                'field': 'document_RIB',
                'filename_field': 'document_RIB_filename',
                'name': _('Bank Details (RIB)'),
            },
        }

        if document_type not in doc_mapping:
            raise ValidationError(_("Invalid document type: %s") % document_type)

        config = doc_mapping[document_type]
        document_data = getattr(partner, config['field'], False)
        document_filename = getattr(partner, config['filename_field'], f"{document_type}.pdf")

        if not document_data:
            raise ValidationError(_(
                "Subcontractor '%s' does not have a %s uploaded."
            ) % (partner.name, config['name']))

        return self.create({
            'contract_id': contract.id,
            'name': config['name'],
            'deliverable_type': document_type,
            'description': _('Valid %s from subcontractor') % config['name'],
            'document': document_data,
            'document_name': document_filename,
            'is_generated': True,
            'generation_date': fields.Datetime.now(),
            'partner_document_type': document_type,
            'source_model': 'res.partner',
            'source_id': partner.id,
            'is_mandatory': True,
            'included_in_contract': True,
        })

    def action_download(self):
        """Download deliverable document"""
        self.ensure_one()

        if not self.document:
            raise ValidationError(_("No document available for download."))

        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/construction.contract.deliverable/{self.id}/document/{self.document_name}?download=true',
            'target': 'new',
        }

    def action_view_source(self):
        """Open source record that generated this deliverable"""
        self.ensure_one()

        if not self.source_model or not self.source_id:
            raise ValidationError(_("No source record linked to this deliverable."))

        return {
            'type': 'ir.actions.act_window',
            'res_model': self.source_model,
            'res_id': self.source_id,
            'view_mode': 'form',
            'target': 'new',
        }
