FROM odoo:18.0

USER root

# Installation des dépendances système pour WeasyPrint
RUN apt-get update && apt-get install -y \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf2.0-0 \
    libffi-dev \
    shared-mime-info \
    && rm -rf /var/lib/apt/lists/*

USER odoo

EXPOSE 8069

CMD ["odoo"]
