# -*- coding: utf-8 -*-
from odoo.tests.common import TransactionCase
from odoo.exceptions import UserError, ValidationError
import base64

class TestConstructionChantier(TransactionCase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        # Create common fixtures
        cls.client_partner = cls.env['res.partner'].create({
            'name': 'Client Test',
            'is_company': True,
        })
        
        cls.stage_draft = cls.env['construction.stage'].create({
            'name': 'Prospect / Étude',
            'code': 'PROSP',
            'sequence': 1,
            'chapter_code': 'AVT',
            'fold': False,
        })
        
        cls.stage_da = cls.env['construction.stage'].create({
            'name': 'Dossier Accepté',
            'code': 'DA',
            'sequence': 2,
            'chapter_code': 'PREP',
            'fold': False,
        })
        
        cls.chapter_avt = cls.env['construction.chapter'].create({
            'name': 'Avant Vente',
            'code': 'AVT',
            'sequence': 10,
        })
        
        # Override stage defaults for testing
        cls.env['ir.config_parameter'].sudo().set_param('construction_core.default_stage_id', cls.stage_draft.id)
        
        cls.chantier = cls.env['construction.chantier'].create({
            'name': 'Chantier Test 001',
            'client': cls.client_partner.id,
            'stage_id': cls.stage_draft.id,
        })

    def setUp(self):
        super().setUp()

    def test_create_chantier_reference(self):
        # GIVEN a freshly created chantier (in setUpClass)
        # THEN reference should be generated by ir.sequence (not New or /)
        self.assertTrue(self.chantier.reference)
        self.assertNotEqual(self.chantier.reference, '/')

    def test_compute_duration_planned(self):
        # GIVEN a chantier with planned dates
        self.chantier.write({
            'date_start_planned': '2025-01-01',
            'date_end_planned': '2025-01-10',
        })
        # WHEN calculating duration
        self.chantier._compute_duration_planned()
        # THEN duration should be 9 days
        self.assertEqual(self.chantier.duration_planned, 9)

    def test_compute_duration_actual(self):
        # GIVEN a chantier with actual dates
        self.chantier.write({
            'date_start_actual': '2025-01-01',
            'date_end_actual': '2025-01-15',
        })
        # WHEN calculating duration
        self.chantier._compute_duration_actual()
        # THEN duration should be 14 days
        self.assertEqual(self.chantier.duration_actual, 14)

    def test_action_move_to_next_stage(self):
        # GIVEN a chantier in Prospect stage
        self.assertEqual(self.chantier.stage_id.code, 'PROSP')
        # WHEN moving to next stage
        self.chantier.action_move_to_next_stage()
        # THEN stage should be DA
        self.assertEqual(self.chantier.stage_id.code, 'DA')

    def test_action_release_guarantee(self):
        # GIVEN a chantier with a pending guarantee
        self.chantier.write({
            'guarantee_status': 'pending'
        })
        # WHEN releasing guarantee
        self.chantier.action_release_guarantee()
        # THEN status should be released
        self.assertEqual(self.chantier.guarantee_status, 'released')
        
    def test_check_progress_95_trigger(self):
        # GIVEN a chantier in a TRAV stage
        stage_t75 = self.env['construction.stage'].create({
            'name': 'Travaux 75%',
            'code': 'T75',
            'sequence': 5,
        })
        stage_lr = self.env['construction.stage'].create({
            'name': 'Levée de Réserve',
            'code': 'LR',
            'sequence': 6,
        })
        self.chantier.write({'stage_id': stage_t75.id})
        
        # WHEN triggered
        self.chantier._check_progress_95_trigger()
        
        # THEN state transitions to LR
        self.assertEqual(self.chantier.stage_id.code, 'LR')
        self.assertEqual(self.chantier.guarantee_status, 'pending')
        self.assertTrue(self.chantier.guarantee_release_date)
