from . import lot_extension
from . import chantier
from . import res_partner
from . import stage
from . import chapter
from . import document
from . import visit
from . import sale_order
from . import tag